# Generated by Django 3.1.2 on 2020-12-03 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locationStreet', models.CharField(blank=True, max_length=50)),
                ('locationCity', models.CharField(max_length=50)),
                ('speedMPH', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
